### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [devsgnr/learning-quantum#1]
I recently came across your project learning-quantum and I noticed that the repository github.com/devsgnr/learning-quantum currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by devsgnr** [comment]
Sure thing @cbjuan - I'd be more than happy to add an open-source license. Honestly, I'm just surprised my repository got noticed by anyone 😅 because it was mainly just for me, and I don't know how useful it'll still be to anyone, since most of the code are really old.

But I guess, I'll never know. Haha 😅 , thanks for the heads-up

**Comment by cbjuan** [comment]
Thank you!
